# Site settings
title: Artificial Intelligence, Cybersecurity, and Programming Languages
email: concurrency@imada.sdu.dk
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://acp.sdu.dk" # the base hostname & protocol for your site
permalink: /news/:year-:month-:day-:title.html
# Build settings
incremental: true
markdown: kramdown
excerpt_separator: "<!--more-->"
group_short: "ACP"
group_name: "Artificial Intelligence, Cybersecurity, and Programming Languages"
exclude: [ "docker", "layout_archive", "utils", "images/communities.graffle", "areas.md", "README.md"]
incremental: false
no_publications: false
