source "https://rubygems.org"

# C liquid engine
gem "liquid-c"

group :jekyll_plugins do
  gem 'jekyll'
  gem 'json'
  gem 'titleize'
  gem 'unicode_utils'
  gem 'jekyll-email-protect'
  gem 'bibtex-ruby'
  gem 'citeproc-ruby'
  gem 'csl-styles'
  gem 'concurrent-ruby'
  gem 'possibly'
end
