source 'https://rubygems.org'

gem 'jekyll', '~> 4.2.0'

group :jekyll_plugins do
  gem 'jekyll-email-protect'
  gem 'jekyll-diagrams'

  # Dependencies of custom plugins.
  gem 'json'
  gem 'titleize'
  gem 'unicode_utils'
  gem 'bibtex-ruby'
  gem 'citeproc-ruby'
  gem 'csl-styles'
  gem 'concurrent-ruby'
  gem 'possibly'
end
